config/routes.rb
Rails.application.routes.draw do
  resources :carts, except: [:index], path: :monpanier
  resources :orders
  root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items 
  resources :users, only: [:show, :edit, :update]
  resources :contact, only: [:index]
  resources :chatons, only: [:index]
  resources :cards, only:[:show]
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :user

  has_many :join_cart_items
  has_many :items, through: :join_cart_items

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :join_cart_items
  has_many :carts, through: :join_cart_items

  has_many :join_order_items
  has_many :orders, through: :join_order_items
  
  validates :title, presence: true,
           length: {minimum: 2}
  validates :description, presence: true,
           length: {maximum: 500}
  validates :price, presence: true
  validates :image_url, presence: true
end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_order_item.rb
class JoinOrderItem < ApplicationRecord
  after_save :after_order, :admin_alert
  belongs_to :order
  belongs_to :item

  def after_order
    UserMailer.after_order(self).deliver_now
  end

  def admin_alert
  	UserMailer.admin_alert(self).deliver_now
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :join_order_items
  has_many :items, through: :join_order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	  after_create :welcome_send
    after_create :create_cart
	  


    has_one :cart
    has_many :orders
  
  
    def welcome_send
    UserMailer.welcome_email(self).deliver_now
    end
    
  def create_cart
    Cart.create(user_id: User.last.id)
  end
 end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def all_items
    u = current_user
    cu = Cart.find_by(user_id: u.id)
    @items = []

    JoinCartItem.where(cart_id: cu.id).each do |item|
      @items << Item.find(item.item_id)
    end

    return @items
  end
  def show
    @cart = current_user_cart
    @items = all_items
    @items_price = only_price_array
  end

  def update
    if current_user
      @cart = current_user_cart
      @item = current_item

      if JoinCartItem.exists?(item_id: @item.id, cart_id: @cart.id) == false
        JoinCartItem.create(cart_id: @cart.id, item_id: @item.id)

        flash[:success] = "Ajouté au panier"
      #  redirect_to(item_path(@item))
            respond_to do |format|
              format.html { redirect_to root_path }
              format.js { }
            end
      else
        flash[:alerte] = "L'item est déjà dans le panier"
        redirect_to(item_path(@item))
      end

    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    JoinCartItem.delete(selected_item_in_cart)

    redirect_to cart_path(Cart.find_by(user_id: current_user.id).id)
  end

  private
  ##########################
  #METHODES POUR UPDATE

  def current_user_cart
    Cart.find_by(user_id: current_user.id)
  end

  def current_item
    Item.find(params[:id])
  end

  ##########################
  #METHODES POUR SHOW

  def only_price_array
    items = all_items

    items_price = []
    items.each do |item_price|
      items_price << item_price.price
    end

    return items_price
  end

  #########################
  #METHODE DELETE
  def selected_item_in_cart
    cu = Cart.find_by(user_id: current_user.id)
    return JoinCartItem.find_by(cart_id: cu.id, item_id: params[:id])
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Paiement de user',
      currency: 'eur',
    })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/chatons_controller.rb
class ChatonsController < ApplicationController
	
	def index
	end 
	
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	
	def index
	end 
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	def index
		@items = Item.all
	end 
	
	def show
		@item = Item.find(params[:id])
	end 
	
end 

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  

  def new
    @order = Order.new
  end

  def create
    @new_order = Order.create(user_id: current_user.id)
    @order = last_order

    @items = all_items
    @items.each do |item|
      JoinOrderItem.create(order_id: @order.id, item_id: item.id)
    end

    if @new_order.save
      destroy
      redirect_to root_path
    end
  end

  def destroy
    cu = Cart.find_by(user_id: current_user.id)
    JoinCartItem.where(cart_id: cu.id).destroy_all
  end


private
  def last_order
    Order.last
  end

end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show

		@user = User.find(params[:id])

	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	
	def update
		@user = User.find(params[:id])
		user_params = params.require(:user).permit(:first_name, :last_name)
		if @user.update(user_params)
			flash[:success] = "Ton profil est modifié"
			redirect_to user_path(:id => current_user.id)
		else
			render :edit
		end
	end
	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def all_items
    u = current_user
    cu = Cart.find_by(user_id: u.id)
    @items = []

    JoinCartItem.where(cart_id: cu.id).each do |item|
      @items << Item.find(item.item_id)
    end

    return @items
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuteKitty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
    <%= stylesheet_link_tag"/stylesheets/bootsrap-2.css" %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
 
    <header>
      <%= render "shared/navbar" %>
    </header>
		
			<%= render "shared/footer" %>
    <%= yield %>
    
  </body>
  
</html>

app/views/shared/_footer.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
 <meta charset="utf-8">
 <title>Titre de la page</title>
 <link rel="stylesheet" href="style.css">
 <link data-brackets-id='19474' rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">
  
</head>

	<body>
		
	<footer >
	<div class="footer">
  <div class="footer-links">
    
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    
  </div>
  <div class="footer-copyright">
		<div class="lead">
 <i class="fas fa-paw"></i>&nbsp;&nbsp;Cute Kitty
  </div>
</div>
		</div>
	</footer>
	</body>
	
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Cute Kitty</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "Les chatons du mois", chatons_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_index_path, class:"nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <% if current_user %>
        
			<button class="btn btn-link my-2 my-sm-0" type="submit"><%= link_to "Mon profil", user_path(:id => current_user.id), class:"nav-link" %></button>
				<button class="btn btn-link my-2 my-sm-0" type="submit"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></button>

    		<% else %>
        <button class="btn btn-link my-2 my-sm-0" type="submit"><%= link_to "Se connecter", new_user_session_path%></button>
        <button class="btn btn-link my-2 my-sm-0" type="submit"><%= link_to "S'inscrire", new_user_registration_path%></button>
      <% end %>
      
      <ul class="nav-item active mr-4 pr-4" >
          <% if current_user == nil %>
            <%= link_to new_user_session_path do%>
              <i class="fas fa-shopping-cart fa-2x "></i>
            <% end%>
          <%else%>
            <%= link_to cart_path(current_user.id) do%>
              <i class="fas fa-shopping-cart fa-2x "></i>
            <% end %>
            <% if current_user.cart.items.length > 0 %>

             <span class="badge badge-pill badge-secondary">  <%= current_user.cart.items.length %></span>
           <% end %>
          <% end %>
        </ul>
    </form>
  
  </div>
</nav>