config/routes.rb
Rails.application.routes.draw do
  resources :carts, except: [:index], path: :monpanier
  resources :orders
  root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items 
  resources :users, only: [:show, :edit, :update]
  resources :contact, only: [:index]
  resources :chatons, only: [:index]
  resources :cards, only:[:show]
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :user

  has_many :join_cart_items
  has_many :items, through: :join_cart_items

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :join_cart_items
  has_many :carts, through: :join_cart_items

  has_many :join_order_items
  has_many :orders, through: :join_order_items
  
  validates :title, presence: true,
           length: {minimum: 2}
  validates :description, presence: true,
           length: {maximum: 500}
  validates :price, presence: true
  validates :image_url, presence: true
end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_order_item.rb
class JoinOrderItem < ApplicationRecord
  after_save :after_order, :admin_alert
  belongs_to :order
  belongs_to :item

  def after_order
    UserMailer.after_order(self).deliver_now
  end

  def admin_alert
  	UserMailer.admin_alert(self).deliver_now
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :join_order_items
  has_many :items, through: :join_order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	  after_create :welcome_send
    after_create :create_cart
	  


    has_one :cart
    has_many :orders
  
  
    def welcome_send
    UserMailer.welcome_email(self).deliver_now
    end
    
  def create_cart
    Cart.create(user_id: User.last.id)
  end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def all_items
    u = current_user
    cu = Cart.find_by(user_id: u.id)
    @items = []

    JoinCartItem.where(cart_id: cu.id).each do |item|
      @items << Item.find(item.item_id)
    end

    return @items
  end
  def show
    @cart = current_user_cart
    @items = all_items
    @items_price = only_price_array
  end

  def update
    if current_user
      @cart = current_user_cart
      @item = current_item

      if JoinCartItem.exists?(item_id: @item.id, cart_id: @cart.id) == false
        JoinCartItem.create(cart_id: @cart.id, item_id: @item.id)

        flash[:success] = "Ajouté au panier"
      #  redirect_to(item_path(@item))
            respond_to do |format|
              format.html { redirect_to root_path }
              format.js { }
            end
      else
        flash[:alerte] = "L'item est déjà dans le panier"
        redirect_to(item_path(@item))
      end

    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    JoinCartItem.delete(selected_item_in_cart)

    redirect_to cart_path(Cart.find_by(user_id: current_user.id).id)
  end

  private
  ##########################
  #METHODES POUR UPDATE

  def current_user_cart
    Cart.find_by(user_id: current_user.id)
  end

  def current_item
    Item.find(params[:id])
  end

  ##########################
  #METHODES POUR SHOW

  def only_price_array
    items = all_items

    items_price = []
    items.each do |item_price|
      items_price << item_price.price
    end

    return items_price
  end

  #########################
  #METHODE DELETE
  def selected_item_in_cart
    cu = Cart.find_by(user_id: current_user.id)
    return JoinCartItem.find_by(cart_id: cu.id, item_id: params[:id])
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Paiement de user',
      currency: 'eur',
    })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/chatons_controller.rb
class ChatonsController < ApplicationController
	
	def index
	end 
	
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	
	def index
	end 
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	def index
		@items = Item.all
	end 
	
	def show
		@item = Item.find(params[:id])
	end 
	
end 

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  

  def new
    @order = Order.new
  end

  def create
    @new_order = Order.create(user_id: current_user.id)
    @order = last_order

    @items = all_items
    @items.each do |item|
      JoinOrderItem.create(order_id: @order.id, item_id: item.id)
    end

    if @new_order.save
      destroy
      redirect_to root_path
    end
  end

  def destroy
    cu = Cart.find_by(user_id: current_user.id)
    JoinCartItem.where(cart_id: cu.id).destroy_all
  end


private
  def last_order
    Order.last
  end

end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show

		@user = User.find(params[:id])

	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	
	def update
		@user = User.find(params[:id])
		user_params = params.require(:user).permit(:first_name, :last_name)
		if @user.update(user_params)
			flash[:success] = "Ton profil est modifié"
			redirect_to user_path(:id => current_user.id)
		else
			render :edit
		end
	end
	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def all_items
    u = current_user
    cu = Cart.find_by(user_id: u.id)
    @items = []

    JoinCartItem.where(cart_id: cu.id).each do |item|
      @items << Item.find(item.item_id)
    end

    return @items
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_addcart.html.erb
<li class="nav-item active mr-4 pr-4" >
<%= link_to cart_path(current_user.id) do%>
  <i class="fas fa-shopping-cart fa-2x "></i>
<% end %>
<span class="badge badge-pill badge-secondary">  <%= current_user.cart.items.length %></span>

</li>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/index.html.erb
<p>lol</p>

app/views/carts/show.html.erb
<br> <br><div class="jumbotron-cart">
  <h1 align="center">Mon panier</h1>
</div><br><br>

<div class="container">
  <div class="card mb-3 shadow-lg">
    <div class="card-header bg-light text-dark">
      <h4> Mes articles
      </h4>
    </div>

    <div class="card-body">
      <% if current_user.cart.items.empty? == false %>
        <% @items.each do |item| %>
          <div id="item-<%= item.id%>">
          <div class="row num" >
            <div class="col-12 col-sm-12 col-md-2 text-center">
              <img class="img-responsive shadow" src="<%= item.image_url %>" alt="prewiew" width="100%" height="auto">
            </div>
            <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
              <%= link_to item_path(item.id), class:"btn btn-link disabled" do%>
                <h4 style="text-transform: uppercase" ><strong><%= item.title %></strong></h4>
                <p><%= item.description %></p>
              <% end %>
            </div>
            <div class="col-8  col-md-4 justify-content-between  row ">
              <div class="col-4 text-md-right align-self-center" style="padding-top: 5px; ">
                <h6 class="text-muted"><strong><%= item.price %> €</strong></h6>
              </div>
              <div class="col-4 text-md-right align-self-center" style="padding-top: 5px;">
                  <h6 class="text-muted">x 1</h6>
              </div>
              <div class="col-4 text-right align-self-center" >
                <%= form_with(url: cart_path(item.id), method: 'delete') do %>
                  <%= button_tag(type: "submit", class:"btn btn-secondary shadow-sm") do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          </div>
          <hr>
        <% end %>
<br><br><%= form_tag charges_path do %>
        <div class="card-footer" style="d-flex ; height: 6em; ">
          <div class="float-right">
            <div style="margin: 5px">
                Total : <b><%= @items_price.sum %> €</b>
            </div>
               <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="Validez votre achat de <%= @items_price.sum %> € !"
                      data-amount="<%= @items_price.sum * 100%>"
                      data-locale="auto"
                      data-label="Commander">
                  </script>
      <% else %>
      <% end %>
    </div>
  </div>
      <% end %>
</div>

app/views/carts/update.js.erb
$(document).ready(function() {
$('#number').hide().html("<%= j render 'addcart'%>").fadeIn("slow");
console.log($('#number').find('li'))
$('#flash').hide().html("<div class='alert alert-dismissible alert-success'><h3> Ajouté au panier !</h3></div>").fadeIn("slow");
});

app/views/charges/create.html.erb
<br><br><h2 align="center">Merci, votre paiement de 5.00€ a bien été pris en compte</h2>
<br><br>

<div align="center">
<%= link_to "Retour à la page d'accueil", root_path, class: "btn btn-primary" %>
</div>

app/views/charges/new.html.erb
<br><br><%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <div align="center">
    <label class="amount">
      <h2>Total à payer: 5.00€</h2>
    </label>
      </div>
  </article>
<div align="center">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Paiement"
          data-amount="500"
          data-currency="eur"
          data-locale="auto"></script>
    </div>
<% end %>

app/views/contact/index.html.erb
<div class="jumbotron2", align="center">
  <h3 class="display-4" style="color:white">Contactez-nous! </h3><br><br><br><br>
  <p class="lead"></p>
  
  <p></p>
  <p class="lead">
    <a></a>
  </p>
</div>


<div class="col-sm-6 col-md-4 mb-7 mb-md-0">
          <h2 class="h4">Nice, France</h2>
          <span class="d-block text-secondary">Office</span>

          <hr class="my-5">

          <address>
            <!-- Contacts List -->
            <ul class="list-unstyled text-secondary">
              <li class="media align-items-center pb-2"> 
								<i class="fas fa-thumbtack"></i>
								&nbsp;&nbsp;&nbsp;
                <div class="media-body">
                    Cute Kitty, la rue des cute kitties, Nice 
                </div>

              </li>

              <li class="media align-items-center py-2">
								<i class="fas fa-clock"></i>
								&nbsp;&nbsp;&nbsp;
                <div class="media-body">
                  Lun-Ven: 9h - 18h
                </div>
              </li>

              <li class="media align-items-center py-2">
                <i class="fas fa-phone"></i>
								&nbsp;&nbsp;&nbsp;
                <div class="media-body">
                  (+33) 6.23.45.54.22
                </div>
              </li>
							
							<li class="media align-items-center py-2">
                <i class="far fa-envelope"></i>
								&nbsp;&nbsp;&nbsp;
                <div class="media-body">
                  cutekitty@cutekitty.com
                </div>
              </li>
            </ul>
            <!-- End Contacts List -->
          

app/views/items/show.html.erb
<% if flash[:alerte] %>
  <div class="alert alert-dismissible alert-success" role="alert">
      <h3><%= flash[:alerte] %></h3>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<div class="container mt-4" >
  <div class="card shadow-lg">
    <div class="row banniere">
      <div class="col-8">
        <img  src="<%= @item.image_url %>" style="height: auto;width: 100%;">
    </div>
    <div class="col-4 d-flex row flex-column">
      <div class="container mt-4">
        <h1 style="text-transform: uppercase"><bold><%= @item.title %></bold> </h1><br><br>
        <p><strong>Description :</strong></p>
        <p><%= @item.description %></p>
      </div>

      <div class="modal-footer mt-auto p-2 bd-highligh justify-content-between">
        <span class="badge badge-pill badge-success  pt-2"><h5><%= @item.price %> €</h5></span>

        <%= form_with(url: cart_path, method: 'patch') do %>
          <%= button_tag(type: "submit", class: "btn btn-default") do %>
            <span class="btn btn-button btn-primary"><i class="fas fa-cart-arrow-down pr-2"></i> Add to cart !</span>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>
</div>
<div class= "mt-4 pt-4">
<div id="flash"></div>
</div>
<br>
<br><br><br><br><br>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<section id="cover">
<div id="cover-caption">
    <div id="container" class="container">
      <div class="row text-white ">
        <div class="col-sm-6 offset-sm-3 text-center">
          <br>
          <h1 class="text-center"> Complète ton profil </h1>
          <br>
          <div class="info-form">
						<div class="form-group">
							<h5 class="text-left">Prénom</h5>
							<%= f.text_field :first_name, class: 'form-control' %>
							<br>
  						<h5 class="text-left">Nom</h5>
							<%= f.text_field :last_name, class: 'form-control' %>
							<br>
					 	</div>
					 	<div class="form-group">
						<div class="actions">
            <%= f.submit "Enregistrer",class:"btn btn-success"%>
          </div>
							<br><br>
							<%= link_to "Back", :back %>
					 	</div>
				 </div>
			 </div>
		 </div>
	 </div>
	</div>
</section>
	 

					 	<% end %>

app/views/users/show.html.erb
<br></br>
<div class="text-center">
<h1>Bienvenue sur ton profil</h1>
</div>
<hr>
<br><br>
<div class="row">
	<div class="container justify-content-center">
<div class="card border-primary mb-3">
  <div class="card-body">
    <h4 class="card-title">Mes informations</h4>
    <h6 class="card-subtitle mb-2 text-muted">Mon prénom : <%= @user.first_name%></h6>
		 <h6 class="card-subtitle mb-2 text-muted">Mon nom : <%= @user.last_name%></h6>
		 <h6 class="card-subtitle mb-2 text-muted">Mon email : <%= @user.email%></h6>
		 <%= link_to "Modifie ton profil", edit_user_registration_path, class: "card-link" %>
		 <%= link_to "Complète ton profil", edit_user_path, class: "card-link" %>
     
  </div>
	<br>
</div>
	<div class="card border-primary mb-3">
  <div class="card-body">
    <h4 class="card-title">Mes commandes</h4>
    <h6 class="card-subtitle mb-2 text-muted"></h6>
    <p class="card-text"></p>
    <a href="#" class="card-link"></a>
    <a href="#" class="card-link"></a>
  </div>
</div>
</div>
	</div>

app/views/welcome/index.html.erb
  <div class="jumbotron" align="center">
  <h1 class="display-4" style="color:white">Bienvenue sur CuteKitty </h1><br><br><br><br>
  <p class="lead" style="color:white">Sur ce site tu peux trouver les photos des chats les plus mignons du monde </p>
  <hr class="my-4">
  <p  style="color:white">Ne perds plus de temps procure toi la tienne dès à présent</p>
</div>

<div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <% Item.all.each do |item| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <img class="img-responsive shadow" src="<%= item.image_url %>" alt="prewiew" width="100%" height="auto">
            <div class="card-body">
              <p class="card-text" style="text-transform: uppercase"><%=  item.title%></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to "En savoir plus", item_path(item.id), class: "btn btn-primary" %> 
                </div>
                <small class="text-muted">Prix : <%=  item.price%></small>
              </div>
            </div>
          </div>
        </div>
       <% end %>
    </div>
  </div>
</div>